import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProviderLayout } from "@/components/theme-provider";
import Link from "next/link";
import StyledComponentsRegistry from "@/lib/registry";
import ReactQueryProvider from "@/utils/queryProvider";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: " Pokemon Gallery",
  description: "Generated by create next app & PokeAPI",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProviderLayout attribute="class" defaultTheme="dark">
          <ReactQueryProvider>
            <StyledComponentsRegistry>
              <main className="flex min-h-screen flex-col items-center p-12">
                <div className="z-10 w-full  max-w-5xl items-center justify-between text-sm lg:flex">
                  <Link href="/">
                    <aside className="flex flex-row gap-2">
                      {/* <Image
                        src="./Poke_Ball_icon.svg"
                        alt="logo"
                        width={35}
                        height={35}
                        className="object-contain"
                      /> */}
                      <h2 className="text-2xl text-bold">PokemonGallery</h2>
                    </aside>
                  </Link>
                </div>
                {children}
              </main>
            </StyledComponentsRegistry>
          </ReactQueryProvider>
        </ThemeProviderLayout>
      </body>
    </html>
  );
}
